### ISSUE TITLE
Отключить вывод заголовка по умолчанию.

### ISSUE THREAD

**Issue by lavrentiev** [loveorigami/yii2-notification-wrapper#13]
Отключить вывод заголовка по умолчанию, если он не был указан.

**Comment by lavrentiev** [comment]
Ну или дать возможность задать свой перевод заголовков по умолчанию.

**Comment by loveorigami** [comment]
Возможность, в принципе, есть.
Создаешь свой класс, наследуемый от выбранного слоя layer (Alert, Growl....), в котором переопределяешь метод setTitle()
https://github.com/loveorigami/yii2-notification-wrapper/blob/master/src/layers/Layer.php#L100

Также можно и ничего не возвращать, тогда и выводится ничего не будет.

Можно добавить опцию, `не выводить титлы`, если в этом есть острая необходимость.

**Comment by lavrentiev** [comment]
Да это понятно, я просто предложил, тебе это сделать если интересно 👍

**Comment by loveorigami** [comment]
Да, спасибо. Опцию отключения заголовков, в принципе, можно добавить.
А вот свои переводы - только через наследование )
