### ISSUE TITLE
Tag 6.7.1 missing on packagist (auto-update broken?)

### ISSUE THREAD

**Issue by schmunk42** [loveorigami/yii2-notification-wrapper#20]
Only 6.7 is available, see https://packagist.org/packages/loveorigami/yii2-notification-wrapper

**Comment by loveorigami** [comment]
I am not adding version to composer ).
https://github.com/loveorigami/yii2-notification-wrapper/blob/master/composer.json#L4
Now it v 6.7.2

**Comment by loveorigami** [comment]
Fix it. Thanks!

**Comment by schmunk42** [comment]
Thank you.

One thing: https://getcomposer.org/doc/04-schema.md#version

> The version of the package. In most cases this is not required and should be omitted (see below).

The version is usually read from a tag, I'd suggest to remove it (**no** new immediate release required) - it's more confusing when it gets out-of-sync.

**Comment by loveorigami** [comment]
Thanks for information. I am delete version 6.7.2

**Comment by schmunk42** [comment]
You might need to trigger a manual update on packagist for it to recognize 6.7.1 - it hasn't appeared yet.

**Comment by loveorigami** [comment]
I am re-update release with composer.json, because packagist don't see v 6.7.1.
