### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by AlessandroCuba** [loveorigami/yii2-notification-wrapper#22]
Hallo,

Thank for your extension, but maybe you can do this:

Example` 'layerClass' => 'lo\modules\noty\layers\Noty'  ---> 'layerClass' => Noty::NOTY_LAYER or Noty::GROWL_LAYER`

thank

**Comment by loveorigami** [comment]
No, because layer - It is class, not constant. See more in folder src

**Comment by AlessandroCuba** [comment]
if I understand that, but in your code you have declared DEFAULT LAYER, in the same way that you could declare the others

your code
```
/** @const default Layer */
    const DEFAULT_LAYER = 'lo\modules\noty\layers\Alert';
```

my suggestion

```
/** @const default Layer */
    const DEFAULT_LAYER = 'lo\modules\noty\layers\Alert';

/** @const default Layer */
    const NOTY_LAYER => 'lo\modules\noty\layers\Noty';
```

**Comment by loveorigami** [comment]
It is not goood idea.
Because in IDE (as phpStorm) I can click by class

```
use lo\modules\noty\Wrapper;

echo Wrapper::widget([
    'layerClass' => lo\modules\noty\layers\Noty::class,
    'layerOptions'=>[
        // for custom layer
        'registerAnimateCss' => true,
        'registerButtonsCss' => true
    ],
]);
```

and see all property for this class.

And I don't errors, such as here #23

**Comment by loveorigami** [comment]
If you want autocompleate in IDE
use as
```
use lo\modules\noty\Wrapper;
use lo\modules\noty\layers;

echo Wrapper::widget([
    'layerClass' => layers\Noty::class,
    'layerOptions'=>[
        // for custom layer
        'registerAnimateCss' => true,
        'registerButtonsCss' => true
    ],
]);
```

after type
```'layerClass' => layers\``` you get all Layers

**Comment by AlessandroCuba** [comment]
ok.. Thank
