### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by Beaten-Sect0r** [loveorigami/yii2-notification-wrapper#6]
https://github.com/loveorigami/yii2-notification-wrapper/blob/79bfbf161a569095c43bc06376305635f4d938e5/src/widgets/layers/Alert.php#L35
получается что шрифт может быть не у всех, как вариант можно заменить иконки на glyphicons.

**Comment by loveorigami** [comment]
Я использую fa в своих проектах "по умолчанию", т.к он более обширен по наличию иконок. 
Например https://github.com/rmrevin/yii2-fontawesome

Для себя можно установить любой свой слой
https://github.com/loveorigami/yii2-notification-wrapper/blob/79bfbf161a569095c43bc06376305635f4d938e5/src/widgets/layers/Alert.php#L18
например

``` php
 echo Wrapper::widget([
      'layerClass' => 'common\notylayers\GlyphiconsAlert',
  ]);
```

в котором прописать любые свои иконки хоть классом, хоть картиной и тп...
т.е. переопределить 
https://github.com/loveorigami/yii2-notification-wrapper/blob/79bfbf161a569095c43bc06376305635f4d938e5/src/widgets/layers/Alert.php#L32

**Comment by Beaten-Sect0r** [comment]
Хорошо.
