### ISSUE TITLE
Unable to set custom title in a notification

### ISSUE THREAD

**Issue by keeprock** [loveorigami/yii2-notification-wrapper#7]
First of all. THANK YOU FOR YOUR MODULE. Its such a pain to get notification working inside Yii2, that I'd a breath of relief after I've seen your plugin actually works.

Start using your module and found an issue - there is no way to change a title of notification. Maybe that comes by design, but for me its a critical feature to have. Take a look at this code in Wrapper.php

```
  protected function getFlashes($layer)
    {
        $session = \Yii::$app->session;
        $flashes = $session->getAllFlashes();
        $options = $this->options;
        $result = [];

        foreach ($flashes as $type => $data) {
            $data = (array)$data;
            $type = (in_array($type, $this->types)) ? $type : self::TYPE_INFO;

            foreach ($data as $i => $message) {
                $result[] = $layer->getNotification($type, $message, $options);
            }

            $session->removeFlash($type);
        }

        if ($this->isAjax) {
            return Html::tag('script', implode("\n", $result));
        }

        return $this->view->registerJs(implode("\n", $result));
    }
```

Especially this line `$type = (in_array($type, $this->types)) ? $type : self::TYPE_INFO;`

Only option is either having a prescribed title or a title TYPE_INFO. There is no way to set it.

I created a fork of this. You may take a look at it, I will point a few differences here after I've completed everything.

**Comment by keeprock** [comment]
https://github.com/keeprock/yii2-notification-wrapper/commit/e2018896998de2a9569bb31aec74f991b160b152

**Comment by keeprock** [comment]
I did not test it against other layers, only Growl.

**Comment by loveorigami** [comment]
Hi, @keeprock 
It may be better to do so
- https://github.com/loveorigami/yii2-notification-wrapper/blob/master/src/widgets/layers/Growl.php#L47

```
$data['title'] = $options['useTitle'] ? $this->getTitle($type) : ''; // not worked now!
```
- In controller you can use (try it)

```
\Yii::$app->getSession()->setFlash('success',   ' <b>MY CUSTOM Title</b><br>noty success');
```

![screenshot 2016-06-23 001](https://cloud.githubusercontent.com/assets/98164/16302618/d6b6c91a-3954-11e6-8c8e-7659bb62ddcc.png)

What you think about it?

**Comment by loveorigami** [comment]
@keeprock , I am added customTitleDelimiter for messages. See readme
